### ISSUE TITLE
xmlsec openssl

### ISSUE THREAD

**Issue by Lewiscowles1986** [mehcode/python-xmlsec#109]
Deploying via wheel to CloudFoundry it seem that there is an error with one of the dependencies of xmlsec

>  2019-08-15T18:08:59.64+0100 [APP/PROC/WEB/0] ERR     import xmlsec
>  2019-08-15T18:08:59.64+0100 [APP/PROC/WEB/0] ERR ImportError: libxmlsec1-openssl.so.1: cannot open shared object file: No such file or directory

**Comment by zanchey** [comment]
https://stackoverflow.com/q/52169554/125549 is probably relevant

**Comment by Lewiscowles1986** [comment]
Sorry to say I solved this last year and must have forgot to action due to no follow-up. The remediation was to modify the buildpack (system definition) to be multi-buildpack to allow apt packages (os distribution controlled) to install the package mentioned, but that was not the only package. This was just to include the shared objects needed. A Better approach is using docker. CloudFoundry and a lot of managed PaaS providers now offer first-class support so people can package.

From this packages perspective the runtime bindings made it difficult to ensure that the correct OS packages were installed. We used some tooling to patch wheels in a vendored distribution, but it could not detect for this library. I did not understand the internals of what it was doing or have a lot of time to fix this, Many of our other python libraries did not experience this issue. 

I've left that role now, so have no access to the code.

**Comment by hoefling** [comment]
@Lewiscowles1986 

> From this packages perspective the runtime bindings made it difficult to ensure that the correct OS packages were installed.

I know what you mean. Because of that, we have actually started releasing prebuilt fat wheels internally that are compliant with [PEP 571](https://www.python.org/dev/peps/pep-0571/) (`manylinux2010`), where every external symbol is statically linked into a single shared object. This resolves the issue of having to compile the C extensions locally. I am now playing with the idea of building and sort of releasing those wheels to the public.

The problem with `xmlsec` is that `libxmlsec1` depends on a crypto library, usually OpenSSL on Linux and this one doesn't have a stable ABI. So imagine the following: we upload `manylinux` wheels on PyPI that don't require installing `libxml2`, `libxmlsec1` or `libcrypto` at all because they ship everything that is needed. People install them. Then a new heartbleed happens. Even if we immediately build a new fat wheel against the fixed OpenSSL version, there's no way to tell the users to update, so they will continue to use a potentially hazardous installation.

I will probably build and release `manylinux2010` wheels (and by the chance, the fat wheels for MacOS), but won't upload them to PyPI and store them somewhere else instead (GH releases or whatever) so everyone should be aware of trading security against the compilation fuss.

**Comment by Lewiscowles1986** [comment]
I totally understood the limitation as OpenSSL now you mention it, was I believe something we also had to bundle with the xmlsec dev. I think it might have been two OpenSSL packages, but maybe it was two xml libraries. It all looks fairly common, but bit-rot in the brain is bad.

I wish I'd gisted the solution now so I could reference it. I kind of filed it under `overcoming combative technologies` in my mind. Buildpacks and similar are a little flawed in what they do to system management of libraries. Wheels are similarly limited, but without the limitations they would be nebulous and even harder to think about.

 It's not really python-xmlsec bindings issue that some vendors have problematic deployment patterns. I'll close.
