### ISSUE TITLE
v0.3.3 broken on gcc 4.x (so it appears)

### ISSUE THREAD

**Issue by mehcode** [mehcode/python-xmlsec#12]
#11 
#9 
#10

**Comment by balavec** [comment]
I have the same problem. It seems I can not install it. But it works on gcc version 5.1

**Comment by mehcode** [comment]
@bgaifullin 

I merged in #13 but now I get

```
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/ryan/Workspace/python-xmlsec, inifile: 
collected 12 items 

tests/examples/test_decrypt.py ..
tests/examples/test_encrypt.py FF
tests/examples/test_sign.py .FF[1]    14753 segmentation fault (core dumped)  py.test

```

**Comment by bgaifullin** [comment]
I will see what happens. Thank you.

**Comment by pitbulk** [comment]
@mehcode , @bgaifullin  any progress? Same issue here Ubuntu 14.04   gcc 4.8.4.
[Not able to install xmlsec 0.3.1 or 0.3.3](https://github.com/mehcode/python-xmlsec/issues/11#issuecomment-162317587) with different cython versions.

**Comment by bgaifullin** [comment]
I found root cause:
I most systems the xmlsec is built without support dynamic load crypto library. that means all methods from file app.h do no work. 
As workaround I can switch to use openssl implementation directly, BTW (now only openssl implementation is used).
Since cython does not support macroses I do not know how to properly fix this in cython implementation.
from my side, the best solution is re-implement this part on pure C instead of cython.

**Comment by bgaifullin** [comment]
I prepared PR.
I am sorry, that I needs so much time to fix this.
@mehcode can you share your opinion about get rid of cython and re-implement code in pure C.

**Comment by mehcode** [comment]
This looks to be fixed finally. Great work @bgaifullin 

---

About a pure python approach.. `hashlib` and `lxml` should be all we really need here. I'd merge something that removed cython and still passed the tests.
