### ISSUE TITLE
Missing git tag for 1.3.10 release

### ISSUE THREAD

**Issue by felixonmars** [mehcode/python-xmlsec#168]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by hoefling** [comment]
@felixonmars sorry, my bad! Added the tag. The problem with the tags is that I'd like to push releases to PyPI from the CI, but don't have access to the Github actions configurations for the project. Thus I have to push the tags to my own fork in order to release. @mehcode it seems you're the only one with the access to secrets as the project author. Can you add one PyPI upload token to [secrets](https://github.com/mehcode/xmlsec/settings/secrets/actions) and [encrypt another one for Appveyor](https://ci.appveyor.com/tools/encrypt) and drop it here? This would enable automatic releases on new tag push.

**Comment by shepdelacreme** [comment]
Is there a proper release tarball available for `1.3.10`? Not having access to the version tarball in the standard `xmlsec-version.tar.gz` is causing havoc in our build/deploy processes.

![Screen Shot 2021-05-04 at 2 09 58 PM](https://user-images.githubusercontent.com/5123728/117049781-9d811180-ace2-11eb-8736-c7f2e0d95d24.png)

**Comment by hoefling** [comment]
@shepdelacreme done: [1.3.10](https://github.com/mehcode/python-xmlsec/releases/tag/1.3.10)
